language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - bin
        - vendor

addons:
    firefox: "47.0.1"

matrix:
    include:
        - php: 7.1
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini
    - composer update $COMPOSER_FLAGS
    - wget --no-clobber -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar bin/selenium.jar > /dev/null 2>&1 &
    - sleep 5

script:
    - bin/phpspec run -f progress -vvv
    - bin/behat --no-snippets --verbose --profile=travis -vvv

after_failure:
    - cat /tmp/FSiAdminTranslatableBundle/logs/test.log
    - cat server.log
