language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

matrix:
    include:
        - php: 5.4
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 5.5
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.6.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.7.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.8.*
        - php: 5.6
        - php: 7.0
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [[ $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n --no-update; fi;
    # Avoid issues on composer update
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer update $COMPOSER_FLAGS

install:
    - wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.46.0.jar > /dev/null 2>&1 &
    - sleep 5

script:
    - bin/phpspec run -f progress -vvv
    - bin/behat --no-snippets --verbose --profile=travis -vvv

after_failure:
    - cat server.log

notifications:
    irc: "irc.freenode.org#fsi-open"
